### ISSUE TITLE
您好 请问MR1的控制是开环控制吗 定位系统是采用激光测距和陀螺仪结合的定位方式吗

### ISSUE THREAD

**Issue by Lizh-ucas** [NEUACTION/2019-MR1#2]

**Comment by WuYuJJ** [comment]
> _没有提供说明。_

您好，MR1有用到位置闭环和速度闭环。
激光和陀螺仪有相互结合定位。正交编码轮和陀螺仪组成定位系统，激光矫正定位系统，辅助定位。
感谢提问~

**Comment by Lizh-ucas** [comment]
> > _没有提供说明。_
> 
> 您好，MR1有用到位置闭环和速度闭环。
> 激光和陀螺仪有相互结合定位。正交编码轮和陀螺仪组成定位系统，激光矫正定位系统，辅助定位。
> 感谢提问~

谢谢啦
