### ISSUE TITLE
您好，请问MR1的轨迹跟踪是怎样实现的呢？

### ISSUE THREAD

**Issue by yanglianoo** [NEUACTION/2019-MR1#3]
您好，请问MR1的轨迹跟踪是采用什么方式的呢？

**Comment by Lizh-ucas** [comment]
if else
？

**Comment by yanglianoo** [comment]
不是 我的意思是离散点路径的跟踪怎样能跟踪得准确且速度较快

**Comment by Lizh-ucas** [comment]
我也在思考这个问题




------------------ 原始邮件 ------------------
发件人: "yanglianoo"<notifications@github.com>; 
发送时间: 2019年9月21日(星期六) 下午4:44
收件人: "NEUACTION/Robocon2019-MR1"<Robocon2019-MR1@noreply.github.com>; 
抄送: "李志豪"<1312592330@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [NEUACTION/Robocon2019-MR1] 您好，请问MR1的轨迹跟踪是怎样实现的呢？ (#3)




不是 我的意思是离散点路径的跟踪怎样能跟踪得准确且速度较快

**Comment by Lizh-ucas** [comment]
上一个回答只是抖了个机灵

**Comment by WuYuJJ** [comment]
> 您好，请问MR1的轨迹跟踪是采用什么方式的呢？
您好，MR1的轨迹跟踪只用了PD控制。
