### ISSUE TITLE
请教 MR1车是如何得到运行轨迹的？

### ISSUE THREAD

**Issue by xiaoliangstd** [NEUACTION/2019-MR1#4]
您好，请问是通过什么算法得到运行轨迹？A*算法？还是

还有很好奇，全场定位系统是和激光测距信息一起进行卡尔曼滤波吗？或者从这两套系统得到的信息是如何整合在一起的？
由于没有这方面积累，想了解学习下。
谢谢！

**Comment by WuYuJJ** [comment]
您好，并没有通过什么算法得到运行轨迹，仅仅是根据比赛规则在制图软件里画出来的，至于您提的使用A*等等这样的得出轨迹的算法我们也在尝试，如果您有好的算法欢迎交流。
关于定位系统和激光的整合不在运动控制的范畴里，并未开源。
