### ISSUE TITLE
您好，请教关于坐标系建立的问题。

### ISSUE THREAD

**Issue by Norach-I** [NEUACTION/2019-MR1#6]
movebase中有两个坐标系转换的函数，一个是世界换机体，另一个是机体换轮系。请问世界坐标系，机体坐标系，轮系坐标系分别是怎样定义坐标系朝向的？还有一个问题就是在角度限制limit函数中，注意到建立了一个静态变量，每次加一减一，而且在if语句中有一个100的数值比较，请问这个有什么技巧或者作用嘛？非常感谢

**Comment by WuYuJJ** [comment]
不好意思才看到，久等了~

世界坐标系是定位系统提供的全局坐标系；机体坐标系是在机器人机身上建立的坐标系；轮系坐标系是在每个舵轮上建立的坐标系，是用来把舵轮的航向转换为航向电机角度命令的。

角度限制limit函数，是一个递归函数。由于我们在控制机器人的姿态角以及舵轮的航向角时，都是把角度范围限制在-180到0到180度来处理的，这样用的好处是可以很方便的处理优弧与劣弧、锐角与钝角的情况。因此，使用了这样一个递归函数，将角度信息处理在一定范围内。
至于100这个数值~ 随便给的，我们觉得100次应该够用了~

**Comment by Norach-I** [comment]
哈哈哈，感谢答复，第一个问题我想问的是"坐标系的朝向"，也就是x,y轴的指向，哈哈哈。关于三个坐标系类型的定义我是知道的。
